weights: ''
cfg: ./models/neuromorphic_SITS_yolov5s.yaml
data: ../data_SITS.yaml
hyp: data/hyp.scratch.yaml
epochs: 1000
batch_size: 16
img_size:
- 128
- 128
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 8
project: runs/train
entity: null
name: yolov5s_SITS_results
exist_ok: false
quad: false
linear_lr: false
world_size: 1
global_rank: -1
save_dir: runs/train/yolov5s_SITS_results3
total_batch_size: 16
